### ISSUE TITLE
Changing stage causes error

### ISSUE THREAD

**Issue by chkrause** [serverless-stack/sst#1906]
Initially I deployed the Stack using this command:
 npx sst deploy --stage CKR--region eu-central-1
 
 So far so good this works quite well.
 
 Now I want to change the stage only and get this strange error message.
 
  npx sst deploy --stage dev --region eu-central-1
Using stage: dev
Preparing your SST app

ParameterNotFound: null
    at Request.extractError (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.callListeners (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\01_Projects\zendesk_eventbridge\zendesk_events\node_modules\aws-sdk\lib\request.js:38:9)

**Comment by fwang** [comment]
Hey @chkrause hmm.. that's strange that it works in one stage but not another.

Can you see if it just fails for the `dev` stage, or fails for all stages that's not named `CKR`?

Also, can you try commenting out constructs/stacks from your app and see if it's a specific construct that's causing this?

**Comment by chkrause** [comment]
Sorry my fault, I figured out why it doesn't work: SSM Parameter wasn't defined for this stage.

**Comment by fwang** [comment]
Ah glad u figured it out. Do u mind sharing a snippet of how you are referencing the SSM Parameter that leads to this error?

We might be able to catch it and throw a friendlier error instead.

**Comment by chkrause** [comment]
```
const connection = new events.Connection(stack, 'Connection', {
    authorization: events.Authorization.apiKey('Authorization', SecretValue.unsafePlainText(await createAuthentication(UserEmailParam, UserAPIkeyParam))),
    description: 'Connection with API Key Authorization',
  });
```

...

```
async function getParameter(name: string, decripted: boolean = false) {
  var params = {
    Name: name, /* required */
    WithDecryption: decripted
  };
  var data = await ssm.getParameter(params).promise().catch(e => { 
    console.error('Could not retrieve SSM Parameter: ' + name)
    throw (e);
  });
  return data.Parameter?.Value;
}
```
