### ISSUE TITLE
AppSyncApi v1 construct doesn't support AWS directives

### ISSUE THREAD

**Issue by smacker** [serverless-stack/sst#2104]
Discovered it during migration from v0 to v1.

**Steps to reproduce:**

Create 2 files, e.g. `mutations.graphql` and `queries.graphql`. Use any [AWS directives](https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html) such as `@aws_iam`, `@aws_cognito_user_pools`, `@aws_api_key` or [scalars](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) such as `AWSDate` or `AWSJSON`.

Pass schemas as an array:

```ts
new sst.AppSyncApi(this, `AppSyncApi`, {
      schema: [
        'schema/mutations.graphql',
        'schema/queries.graphql',
      ],
}
```

Run `sst build/start/deploy`.

Result:
```
Error: Unknown directive "@aws_iam".

Unknown directive "@aws_cognito_user_pools".

Unknown directive "@aws_api_key".

Unknown type "AWSDateTime".

    at assertValidSDL (/some/path/node_modules/graphql/validation/validate.js:107:11)
    at buildASTSchema (/some/path/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at buildSchema (/some/path/node_modules/graphql/utilities/buildASTSchema.js:112:10)
    at Array.map (<anonymous>)
    at AppSyncApi.createGraphApi (file:///some/path/node_modules/@serverless-stack/resources/dist/AppSyncApi.js:242:26)
    at new AppSyncApi (file:///some/path/node_modules/@serverless-stack/resources/dist/AppSyncApi.js:48:14)
    at new GraphQlStack (file:///some/path/server/.build/lib/index.js:83:23)
    at Module.main (file:///some/path/server/.build/lib/index.js:533:24)
    at file:///some/path/server/.build/run.mjs:96:22
```

**Problem:**

When schema is defined in more than 1 file `sst` processes them with [graphql.buildSchema](https://github.com/serverless-stack/sst/blob/b51cd3ac640eddb73fb391e57a0e313f44747826/packages/resources/src/AppSyncApi.ts#L686).

This function doesn't know about AWS directives or scalar types like `@aws_iam`, `@aws_cognito_user_pools`, `@aws_api_key`, `AWSDateTime`.

Current workaround is to combine all schemas into a single file and defined schema as a string instead of an array in the construct to bypass `graphql.buildSchema`.

**Comment by dnz-bdeboer** [comment]
Yes, pretty annoying. Any better workarounds?

**Comment by dnz-bdeboer** [comment]
The issue here is that if there is one file, the schema file is passed to AppSync for checking. Which is a bit annoying, as you find errors quite late. If you use an array (even with 1 file), it uses some schema merging tool, which validates the result. If you think you can fix this with `scalar AWSDateTime`, this is something the merge likes, but causes an internal error in appsync when you deploy....

**Comment by dnz-bdeboer** [comment]
In addition to @smacker's solution, here's how I've solved this right now:

```ts
import { print } from "graphql"
import { mergeTypeDefs } from "@graphql-tools/merge"
import { loadFilesSync } from "@graphql-tools/load-files"

export function MyStack({ stack }: StackContext) {

  ...
  // merge schema files
  const schemaTypes = loadFilesSync(path.join('./graphql/types'), { extensions: ['graphql'] })
  const mergedSchema = mergeTypeDefs(schemaTypes)
  const filePath = "./graphql/schema.graphql"
  writeFileSync(filePath, print(mergedSchema));

  const api = new AppSyncApi(stack, "AppSyncApi", {
    schema: filePath,
    ...
  }
}
```

Based on this I suggest sst drops the `buildSchema` call, as it does not verify the schema if there's just one, why do it when there are multiple if you can't do it properly?

**Comment by dnz-bdeboer** [comment]
The problem with my solution is that sst does not detect changes in my individual schema files, i.e. won't recompile.

**Comment by dnz-bdeboer** [comment]
Actually, ignore all that (deleted my previous comments, there was another error), you simply add an `appsync.graphql` file as follows:

```ts
  const api = new AppSyncApi(stack, "AppSyncApi", {
    schema: [
      "graphql/appsync.graphql",
      "graphql/part1.graphql",
      "graphql/part2.graphql",
    ],
  ...
```

And `appsync.graphql` is:

```graphql
scalar AWSDate
scalar AWSTime
scalar AWSDateTime
scalar AWSTimestamp
scalar AWSEmail
scalar AWSJSON
scalar AWSURL
scalar AWSPhone
scalar AWSIPAddress
```

**Comment by dnz-bdeboer** [comment]
The only problem is that if I change `graphql/part1.graphql` sst does not rebuild. I.e. watcher is not picking this up.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
