### ISSUE TITLE
RDS type generation doesn't seem to work

### ISSUE THREAD

**Issue by TimarTimar** [serverless-stack/sst#2129]
Hi,

I'm trying to make type generation work for RDS/postgres10.14

I followed this example: https://github.com/serverless-stack/sst/tree/master/examples/create-sst-rds.
My folder structure, and relevant code are the same.

My versions:
```
    "kysely": "0.21.3",
    "kysely-data-api": "0.1.2",
    "@serverless-stack/resources": "1.15.11"
 ```
 
 My migration file:
 ```
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Kysely, sql } from 'kysely'

/**
 * @param db {Kysely<any>}
 */
export async function up(db) {
  await db.schema
    .createTable('client')
    .addColumn('client_id', 'uuid', (col) => col.primaryKey())
    .addColumn('client_name', 'varchar', (col) => col.notNull())
    .addColumn('slack_token', 'varchar', (col) => col.notNull())
    .addColumn('created_at', 'timestamptz', (col) =>
      col.notNull().defaultTo(sql`CURRENT_TIMESTAMP`)
    )
    .execute()

  await db.schema
    .createTable('channel')
    .addColumn('channel_id', 'varchar', (col) => col.primaryKey())
    .addColumn('client_id', 'uuid', (col) =>
      col.references('client.client_id').onDelete('cascade').notNull()
    )
    .addColumn('channel_name', 'varchar', (col) => col.notNull())
    .execute()
}

/**
 * @param db {Kysely<any>}
 */
export async function down(db) {
  await db.schema.dropTable('client').execute()
  await db.schema.dropTable('channel').execute()
}
```

Both of these options are resulted with the following error, when I try to run this migration from sst-console:

Option1:
```
    types: {
      path: "services/core/sql.generated.ts",
      camelCase: true,
    },
```

Option2:
```
types:"services/core/sql.generated.ts"
```

Error:
```
[0] 73d5a866-161c-41e2-a748-35f57bc5122f ERROR Error: invalid immediate value [object Object] 
[0]  Error: invalid immediate value [object Object]
[0]     at PostgresDataApiQueryCompiler.appendImmediateValue (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:934:19)
[0]     at PostgresDataApiQueryCompiler.visitValue (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:266:18)
[0]     at PostgresDataApiQueryCompiler.visitNode (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
[0]     at PostgresDataApiQueryCompiler.visitDefaultValue (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:824:14)
[0]     at PostgresDataApiQueryCompiler.visitNode (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
[0]     at PostgresDataApiQueryCompiler.visitColumnDefinition (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:367:18)
[0]     at PostgresDataApiQueryCompiler.visitNode (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
[0]     at PostgresDataApiQueryCompiler.compileList (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:116:18)
[0]     at PostgresDataApiQueryCompiler.visitCreateTable (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:343:14)
[0]     at PostgresDataApiQueryCompiler.visitNode (file:///Users/tamo/dev/apex/beconnected/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
[0] dd7a88e7-9751-4182-b782-e64364561fd1 REQUEST tamo-dev-beconnected-Data-rdsMigrationFunction3B4B-ShacP3arHc4X [index.handler] invoked
[0] 
[0] TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
[0]     at open (node:internal/fs/promises:456:10)
[0]     at Object.writeFile (node:internal/fs/promises:795:20)
[0]     at Object.cb (file:///Users/tamo/dev/apex/beconnected/node_modules/@serverless-stack/core/dist/cli/KyselyTypeGenerator.js:49:12)
```

**Comment by TimarTimar** [comment]
With the latest packages for both in my app, and at latest `create-sst-rds` , I'm receiveing type error at services/core/sql.ts .

```
No overload matches this call.
  Overload 1 of 2, '(args: KyselyConfig): Kysely<Database>', gave the following error.
    Type 'DataApiDialect' is not assignable to type 'Dialect'.
      The types returned by 'createDriver().acquireConnection()' are incompatible between these types.
        Type 'Promise<import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/driver/database-connection").DatabaseConnection>' is not assignable to type 'Promise<import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/driver/database-connection").DatabaseConnection>'.
          Type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/driver/database-connection").DatabaseConnection' is not assignable to type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/driver/database-connection").DatabaseConnection'.
            Types of property 'executeQuery' are incompatible.
              Type '<R>(compiledQuery: import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/query-compiler/compiled-query").CompiledQuery) => Promise<...>' is not assignable to type '<R>(compiledQuery: import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/query-compiler/compiled-query").CompiledQuery) => Promise<...>'.
                Types of parameters 'compiledQuery' and 'compiledQuery' are incompatible.
                  Type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/query-compiler/compiled-query").CompiledQuery' is not assignable to type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/query-compiler/compiled-query").CompiledQuery'.
                    Types of property 'query' are incompatible.
                      Type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/query-compiler/query-compiler").RootOperationNode' is not assignable to type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/query-compiler/query-compiler").RootOperationNode'.
                        Type 'SelectQueryNode' is not assignable to type 'RootOperationNode'.
                          Type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/operation-node/select-query-node").SelectQueryNode' is not assignable to type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/operation-node/select-query-node").SelectQueryNode'.
                            The types of 'from.froms' are incompatible between these types.
                              Type 'readonly import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/operation-node/operation-node-utils").TableExpressionNode[]' is not assignable to type 'readonly import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/operation-node/operation-node-utils").TableExpressionNode[]'.
                                Type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/operation-node/operation-node-utils").TableExpressionNode' is not assignable to type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/operation-node/operation-node-utils").TableExpressionNode'.
                                  Type 'AliasNode' is not assignable to type 'TableExpressionNode'.
                                    Type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/operation-node/alias-node").AliasNode' is not assignable to type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/operation-node/alias-node").AliasNode'.
                                      Types of property 'node' are incompatible.
                                        Type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely/dist/cjs/operation-node/alias-node").AliasNodeChild' is not assignable to type 'import("/Users/tamo/dev/learning/sst/examples/create-sst-rds/services/node_modules/kysely-data-api/node_modules/kysely/dist/cjs/operation-node/alias-node").AliasNodeChild'.
                                          Type 'SelectQueryNode' is not assignable to type 'AliasNodeChild'.
  Overload 2 of 2, '(args: KyselyProps): Kysely<Database>', gave the following error.
    Type 'DataApiDialect' is not assignable to type 'Dialect'.ts(2769)
kysely.d.ts(361, 14): The expected type comes from property 'dialect' which is declared here on type 'KyselyConfig'
kysely.d.ts(357, 14): The expected type comes from property 'dialect' which is declared here on type 'KyselyProps'
```

**Comment by TimarTimar** [comment]
Managed to solve my issue, by:
- using `kysely-data-api 0.1.3`
- changing
this:
```
   .addColumn('created_at', 'timestamptz', (col) =>
     col.notNull().defaultTo(sql`CURRENT_TIMESTAMP`)
   )
```
to:
```
  .addColumn('created_at', 'timestamptz', (col) =>
      col.notNull().defaultTo('NOW()')
    )
```
