### ISSUE TITLE
Cannot find a lock file (v1.15.16) [Rush + pnpm]

### ISSUE THREAD

**Issue by shechter** [serverless-stack/sst#2150]
Using `rush` and `pnpm`
```
$ rushx deploy --stage=dev --verbose
```
works fine with 
```
     "@serverless-stack/cli": "1.15.10",
    "@serverless-stack/resources": "1.15.10",
    "@serverless-stack/core": "1.15.10",
```
but when I upgrade to `1.15.16`  it fails at
```

Error: Cannot find a lock file
    at getModuleManager (file:///Users/shechter/src/backend/common/temp/node_modules/.pnpm/@serverless-stack+core@1.15.16_pg@8.8.0/node_modules/@serverless-stack/core/dist/runtime/handler/node.js:39:11)
    at installNodeModules (file:///Users/shechter/src/backend/common/temp/node_modules/.pnpm/@serverless-stack+core@1.15.16_pg@8.8.0/node_modules/@serverless-stack/core/dist/runtime/handler/node.js:239:50)
    at async Object.bundle (file:///Users/shechter/src/backend/common/temp/node_modules/.pnpm/@serverless-stack+core@1.15.16_pg@8.8.0/node_modules/@serverless-stack/core/dist/runtime/handler/node.js:181:13)
    at async file:///Users/shechter/src/backend/common/temp/node_modules/.pnpm/@serverless-stack+resources@1.15.16_pg@8.8.0/node_modules/@serverless-stack/resources/dist/Function.js:242:33

```

**Comment by joshwils82** [comment]
Im also hitting the same issue using sst and pnpm.

**Comment by shechter** [comment]
@fwang any thoughts on this? I'm still seeing the error and I think it is specifically related to the 
```
  bundle: {
           nodeModules: ['pg'],
   }
``` 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/4543920/203243875-c9cd4f43-a51d-4874-82c1-b35ea4643229.png">

**Comment by fwang** [comment]
@thdxr any idea about this one? Will this still be a problem with SST v2?

**Comment by thdxr** [comment]
Fixed in v2

**Comment by shechter** [comment]
@thdxr what's the timeline on v2?

**Comment by thdxr** [comment]
Hoping to get an RC out this week, you can try it out already check our #sst2 channel on discord
