### ISSUE TITLE
Cannot use Table.X. Please make sure it is bound to this function

### ISSUE THREAD

**Issue by Newbie012** [serverless-stack/sst#2205]
While running `pnpm sst build`, I'm getting the following error:

```
Error: Cannot use Table.EventStore. Please make sure it is bound to this function.
    at Object.get (file:///xxx/node_modules/.pnpm/@serverless-stack+node@1.18.2/node_modules/@serverless-stack/node/util/index.js:8:27)
    at file:///xxx/.build/lib/index.js:666390:20
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async file:///xxx/.build/run.mjs:93:17
```

Trying to debug the flow has led me to this:

![image](https://user-images.githubusercontent.com/10504365/202891782-33d8a2d9-6765-4947-bb25-761528c33727.png)

I'm probably missing something, but why is the target `{}`?

If there's any more information needed, please let me know (there's no issue template).

**Comment by Newbie012** [comment]
I think I found the issue, it has to do with **when** I call it.

I have a module called `x.service.ts` which has something like:

```ts
import { createMicroService } from "@app/shared/core";
import { Table } from "@serverless-stack/node/table";

export const xService = createService({
  name: "xService",
  tables: {
    EventStore: {
      name: Table.EventStore.tableName
    },
  },
});
```

`xService` was used to create lambda handlers, but it was used in the stack itself. Meaning, I imported @serverless-stack/node and called it before the stack was built. To facilitate this, I changed it to:

```ts
import { createMicroService } from "@app/shared/core";

export const xService = createService({
  name: "xService",
  tables: {
    EventStore: {
      name: ({ Table }) => Table.EventStore.tableName
    },
  },
});
```
