### ISSUE TITLE
Pothos / schema / genql

### ISSUE THREAD

**Issue by felipevyg** [serverless-stack/sst#2243]
Package versions:
```
    "@serverless-stack/cli": "1.18.4"
    "@serverless-stack/node": "1.18.4"
    "@serverless-stack/resources": "1.18.4"
    "@pothos/core": "^3.21.0"
    "graphql": "^16.6.0"
```

I'm having some weird issues when using a GraphQL API with Pothos.
My schema is definitely working correctly in the API, what it is not working is the code generation part.
When I run `sst start`, it deploys everything as expected, but prints this error:

```
Failed to extract schema from pothos
TypeError: Cannot read properties of undefined (reading 'toString')
    at join (<project-path>/serverless/node_modules/escodegen/escodegen.js:550:52)
    at CodeGenerator.ClassExpression (<project-path>/serverless/node_modules/escodegen/escodegen.js:2121:26)
    at CodeGenerator.generateExpression (<project-path>/serverless/node_modules/escodegen/escodegen.js:2496:28)
    at CodeGenerator.CallExpression (<project-path>/serverless/node_modules/escodegen/escodegen.js:1885:34)
    at CodeGenerator.generateExpression (<project-path>/serverless/node_modules/escodegen/escodegen.js:2496:28)
    at CodeGenerator.ExpressionStatement (<project-path>/serverless/node_modules/escodegen/escodegen.js:1332:28)
    at CodeGenerator.generateStatement (<project-path>/serverless/node_modules/escodegen/escodegen.js:2509:33)
    at CodeGenerator.Program (<project-path>/serverless/node_modules/escodegen/escodegen.js:1714:43)
    at CodeGenerator.generateStatement (<project-path>/serverless/node_modules/escodegen/escodegen.js:2509:33)
    at generateInternal (<project-path>/serverless/node_modules/escodegen/escodegen.js:2530:28)
```

As I said, the API works fine, though. I can query and mutate data as normal. But nothing is getting into the `graphql/` folder when the genql should work.

Here is my API route config:

```javascript
'POST /graphql': {
  type: 'graphql',
  authorizer: 'Auth0',
  function: {
    handler: 'functions/graphql/graphql.handler',
  },
  pothos: {
    schema: 'services/functions/graphql/schema.ts',
    output: 'graphql/schema.graphql',
    commands: [
      'npx genql --output ./graphql/genql --schema ./graphql/schema.graphql --esm',
    ],
  },
}
```

It's not generating the schema file in that `output` folder, which I assume is preventing genql to do anything.

This is how I generate the Pothos schema in the Lambda function (this is the `services/functions/graphql/schema.ts` specified in the route config):
```
import { builder } from './builder'
import { printSchema, lexicographicSortSchema } from 'graphql'

import './schemas/user.schema'
import './schemas/favourite.schema'

builder.queryType({})
builder.mutationType({})

export const localSchema = builder.toSchema({})
console.log(`SCHEMA`, printSchema(lexicographicSortSchema(localSchema)))
```

The resulting string printed above is the following. (Sorry for being too application-specific)
```
SCHEMA 
type Favourite {
  dateAdded: String!
  favouriteId: String!
  type: String!
}

type Mutation {
  addFavourite(favouriteId: String!, type: String!): Boolean!
  changeUserName(name: String!): User
  removeFavourite(favouriteId: String!): Boolean!
}

type Query {
  isFavourite(favouriteId: String!): Boolean!
  user: User!

  userFavourites(
    type: String
  ): [Favourite!]!
}

type User {
  authId: String!
  email: String!
  id: String!
  name: String
}
```

Any ideas of what is happening there?

UPDATE:
I've pasted that GraphQL schema into `graphql/schema.graphql` and ran the genql command manually. It worked and generated the code. So the problem seems to be related to generating that schema file in the first place.
How does `schema: 'services/functions/graphql/schema.ts'` in the route config works? Is it trying to import the default export, a named one?
I've tried exporting the resulting built schema as default, or named as `schema` but nothing changed.

UPDATE 2:
It seems to be an issue with how I add my types to the SchemaBuilder. I'm using TS interfaces instead of classes.

**Comment by felipevyg** [comment]
Ok, just don't use the Objects in `SchemaBuilder<{ Objects: {} }>({})`. I converted everything to use objectRef instead of using objectType with a string mapping to an interface. Works now.
