### ISSUE TITLE
[SST 2 + Astro] Initial deployment happy path is broken

### ISSUE THREAD

**Issue by ffxsam** [serverless-stack/sst#2391]
The happy path for initial deployment is in a non-working state. Below are the details of the setup as well as the steps to reproduce the various issues.

## System Config
OS: macOS 12.6.2
Node: v18.12.1
Pkg installer: pnpm

## Package Versions
```
dependencies:
astro 2.0.2

devDependencies:
astro-sst 2.0.0-rc.18
aws-cdk-lib 2.55.0
constructs 10.1.156
sst 2.0.0-rc.56
```

## Project Setup
```shell
$ pnpm create astro@latest (default "yes" to all questions)
$ cd sst-test
$ pnpx create-sst@rc (default "yes" to all questions)
```

## Failure Point 1
```shell
$ pnpm sst:deploy
```

This fails and results in:
```
Error: Failed to build function "dist/server/entry.handler"

Trace: Error: Failed to build function "dist/server/entry.handler"
    at file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/constructs/Function.js:190:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at process.<anonymous> (file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/cli/sst.js:54:17)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

Thanks to [Andy Kenward's help](https://discord.com/channels/983865673656705025/1068236979659092038/1069034535938953346), this can be worked around by creating an `.npmrc` file with these contents:

```ini
node-linker=hoisted
```

## Failure Point 2
```shell
$ pnpm sst:deploy
```

It gets further this time thanks to the workaround above, but still fails:

```
✔  Building...

|  Site site/ServerCache AWS::CloudFront::CachePolicy CREATE_COMPLETE
|  Site site/AwsCliLayer AWS::Lambda::LayerVersion CREATE_COMPLETE
|  Site site/S3Uploader/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site Custom::S3AutoDeleteObjectsCustomResourceProvider AWS::IAM::Role CREATE_COMPLETE
|  Site site/ServerFunction/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site site/S3Handler/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site site/CloudFrontInvalidator/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site CustomResourceHandler/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site CustomResourceHandler AWS::Lambda::Function CREATE_FAILED
|  Site site/S3Bucket AWS::S3::Bucket CREATE_FAILED
|  Site LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole AWS::IAM::Role CREATE_FAILED
|  Site site/CloudFrontInvalidator/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_FAILED
|  Site site/S3Bucket AWS::S3::Bucket DELETE_COMPLETE
|  Site site/CloudFrontInvalidator/ServiceRole/DefaultPolicy AWS::IAM::Policy DELETE_COMPLETE
|  Site site/ServerCache AWS::CloudFront::CachePolicy DELETE_COMPLETE
|  Site Custom::S3AutoDeleteObjectsCustomResourceProvider AWS::IAM::Role DELETE_COMPLETE
|  Site site/S3Uploader/ServiceRole AWS::IAM::Role DELETE_COMPLETE
|  Site site/ServerFunction/ServiceRole AWS::IAM::Role DELETE_COMPLETE
|  Site LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole AWS::IAM::Role DELETE_COMPLETE
|  Site site/AwsCliLayer AWS::Lambda::LayerVersion DELETE_COMPLETE
|  Site site/S3Handler/ServiceRole AWS::IAM::Role DELETE_COMPLETE
|  Site site/CloudFrontInvalidator/ServiceRole AWS::IAM::Role DELETE_COMPLETE
|  Site CustomResourceHandler AWS::Lambda::Function DELETE_COMPLETE
|  Site CustomResourceHandler/ServiceRole AWS::IAM::Role DELETE_COMPLETE
⠼  Site site/S3Bucket AWS::S3::Bucket DELETE_IN_PROGRESS
⠋  Site site/CloudFrontInvalidator/ServiceRole/DefaultPolicy     DELETE_IN_PROGR
AWS::IAM::Policy                                                 ESS

✖  Errors
   Site
   CustomResourceHandler: Resource handler returned message: "The role defined for the function cannot be assumed by Lambda. (Service: Lambda, Status Code: 400, Request ID: 14f0d6fa-416e-4435-b389-47399e69a1ce)" (RequestToken: 5d1bd98e-b189-5b6e-38c6-8f2305c8d9a6, HandlerErrorCode: InvalidRequest)
```

**Comment by ffxsam** [comment]
Very strange. On a second `sst:deploy` attempt right after the failure point 2 above, it worked. I didn't change anything in the code or config. Below is the full output:

<details>
<summary>Expand</summary>

```
✔  Building...

|  Site site/ServerCache AWS::CloudFront::CachePolicy CREATE_COMPLETE
|  Site site/AwsCliLayer AWS::Lambda::LayerVersion CREATE_COMPLETE
|  Site LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site site/S3Uploader/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site Custom::S3AutoDeleteObjectsCustomResourceProvider AWS::IAM::Role CREATE_COMPLETE
|  Site site/CloudFrontInvalidator/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site site/ServerFunction/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site site/S3Handler/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site CustomResourceHandler/ServiceRole AWS::IAM::Role CREATE_COMPLETE
|  Site site/S3Bucket AWS::S3::Bucket CREATE_COMPLETE
|  Site CustomResourceHandler AWS::Lambda::Function CREATE_COMPLETE
|  Site LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_COMPLETE
⠴  Site site/ServerCache AWS::CloudFront::CachePolicy CREATE_IN_PROGRESS
|  Site Custom::S3AutoDeleteObjectsCustomResourceProvider AWS::Lambda::Function CREATE_COMPLETE
⠴  Site site/ServerCache AWS::CloudFront::CachePolicy CREATE_IN_PROGRESS
|  Site site/CloudFrontInvalidator/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_COMPLETE
⠴  Site site/ServerCache AWS::CloudFront::CachePolicy CREATE_IN_PROGRESS
|  Site site/ServerFunction/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_COMPLETE
|  Site site/S3Uploader/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_COMPLETE
|  Site LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a AWS::Lambda::Function CREATE_COMPLETE
|  Site site/CloudFrontInvalidator AWS::Lambda::Function CREATE_COMPLETE
|  Site site/ServerFunction AWS::Lambda::Function CREATE_COMPLETE
|  Site site/S3Uploader AWS::Lambda::Function CREATE_COMPLETE
|  Site site/ServerFunction/FunctionUrl AWS::Lambda::Url CREATE_COMPLETE
|  Site site/ServerFunction/LogRetention Custom::LogRetention CREATE_COMPLETE
|  Site site/ServerFunction AWS::Lambda::Permission CREATE_COMPLETE
|  Site site/S3Handler/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_COMPLETE
|  Site site/S3Handler AWS::Lambda::Function CREATE_COMPLETE
|  Site site/S3Deployment Custom::SSTBucketDeployment CREATE_COMPLETE
|  Site site/Distribution/Origin2/S3Origin AWS::CloudFront::CloudFrontOriginAccessIdentity CREATE_COMPLETE
|  Site site/S3Bucket/Policy AWS::S3::BucketPolicy CREATE_COMPLETE
|  Site site/S3Bucket/AutoDeleteObjectsCustomResource Custom::S3AutoDeleteObjects CREATE_COMPLETE
|  Site site/Distribution AWS::CloudFront::Distribution CREATE_COMPLETE
|  Site site/CloudFrontInvalidation Custom::SSTCloudFrontInvalidation CREATE_COMPLETE
|  Site site/Parameter_url AWS::SSM::Parameter CREATE_COMPLETE
⠇  Site site/ServerCache AWS::CloudFront::CachePolicy CREATE_IN_PROGRESS
⠼  Site site/AwsCliLayer AWS::Lambda::LayerVersion CREATE_IN_PROGRESS
⠼  Site site/ServerFunction/FunctionUrl AWS::Lambda::Url CREATE_IN_PROGRESS
⠋  Site site/ServerFunction/LogRetention Custom::LogRetention CREATE_IN_PROGRESS
⠹  Site site/S3Deployment Custom::SSTBucketDeployment CREATE_IN_PROGRESS
⠼  Site site/Distribution/Origin2/S3Origin      CREATE_IN_PROGRESS
AWS::CloudFront::CloudFrontOriginAccessIdentity
⠼  Site site/S3Bucket/Policy AWS::S3::BucketPolicy CREATE_IN_PROGRESS
⠏  Site site/S3Bucket/AutoDeleteObjectsCustomResource CREATE_IN_PROGRESS
Custom::S3AutoDeleteObjects

✔  Deployed:
   Site
   url: https://xx.cloudfront.net
```
</details>

**Comment by ffxsam** [comment]
Removal of stack (`pnpm sst remove`) is also non-functional:

```
Error: The stack output "url" is undefined

Trace: Error: The stack output "url" is undefined
    at file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/constructs/Stack.js:164:23
    at Array.forEach (<anonymous>)
    at EmptyStack.addOutputs (file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/constructs/Stack.js:161:30)
    at EmptyStack.Site (/Users/samh/sst-test/sst.config.ts:14:17)
    at stack (file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/constructs/FunctionalStack.js:20:35)
    at App.stack (file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/constructs/App.js:495:16)
    at Object.stacks (/Users/samh/sst-test/sst.config.ts:12:9)
    at Module.synth (file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/stacks/synth.js:52:20)
    at async file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/cli/commands/remove.js:27:16
    at async Object.handler (file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/cli/commands/remove.js:22:22)
    at process.<anonymous> (file:///Users/samh/sst-test/node_modules/.pnpm/sst@2.0.0-rc.56/node_modules/sst/cli/sst.js:54:17)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by ffxsam** [comment]
Happy to report that all is well now!
