### ISSUE TITLE
SST2: Binding a RemixSite to a function causes a crash in dev mode

### ISSUE THREAD

**Issue by estyrke** [serverless-stack/sst#2392]
When running dev mode in sst2@rc56, it's not possible to bind a RemixSite to a handler:

Stacks:

```typescript
  const site = new RemixSite(stack, "site", {
    path: "frontend/",
  });
 const auth = new Auth(stack, "Auth", {
    authenticator: {
      handler: "services/functions/auth/authenticator.handler",
      environment: {},
      bind: [site],
    },
  });
```

authenticator.ts:
```typescript
import { RemixSite } from "sst/node/site";
...
const google = GoogleAdapter({
  onSuccess: async (tokenset, client) => {
[...]
    const redirect = process.env.IS_LOCAL
      ? "http://localhost:3000/login"
      : RemixSite.site.url + "/login";
[...]
  },
});

export const handler = AuthHandler({
  providers: {
    google,
  },
});
```

When authenticator is invoked, this error is thrown in the CLI:
```Invoked services/functions/auth/authenticator.handler
|  Error: The following RemixSite were not found: site
   Error: The following RemixSite were not found: site
       at replaceWithSsmValues2 (/Users/emilst/Code/lkss/internwebb/node_modules/sst/node/site/index.js:34:15)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at <anonymous> (/Users/emilst/Code/lkss/internwebb/node_modules/sst/node/site/index.js:18:1)
|  Error: Cannot read properties of undefined (reading 'handler')
   TypeError: Cannot read properties of undefined (reading 'handler')
       at file:///Users/emilst/Code/lkss/internwebb/node_modules/sst/support/nodejs-runtime/index.mjs:14646:25
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by TimisRobert** [comment]
You can, you just need to add to the remix site construct dev: { deploy: true }
Would maybe be ideal to have a placeholder or passing a parameter to put into SSM if deploy: false

**Comment by estyrke** [comment]
Yeah, that works as a workaround for now, but it kind of defeats the purpose of not having to deploy sites in dev. 😅

**Comment by fwang** [comment]
@estyrke this should be fixed. Can you give v2.0.7 a try?

**Comment by estyrke** [comment]
Yes, works now! Thanks!
