### ISSUE TITLE
Python: Cannot deploy v2 (`EINVAL`)

### ISSUE THREAD

**Issue by ecumene** [serverless-stack/sst#2469]
## Description

I upgraded our stack to V2 but now I'm running into an error with `sst build`. Curious, I tried using a blank python project and ran into the same problem. I think it's a bug.

## Error:

```bash
❯ npm run build         

> sst-py@0.0.0 build
> sst build

Error: Invalid src or dest: cp returned EINVAL (cannot copy /Users/mitch/<dir>/sst-py to a subdirectory of self /Users/mitch/<dir>/sst-py/.sst/artifacts/c8e724473dea4ba7e3c24ed8758fa55c990c9fe7a6) /Users/mitch/<dir>/sst-py/.sst/artifacts/c8e724473dea4ba7e3c24ed8758fa55c990c9fe7a6

Trace: SystemError [ERR_FS_CP_EINVAL]: Invalid src or dest: cp returned EINVAL (cannot copy /Users/mitch/<dir>/sst-py to a subdirectory of self /Users/mitch/<dir>/sst-py/.sst/artifacts/c8e724473dea4ba7e3c24ed8758fa55c990c9fe7a6) /Users/mitch/<dir>/sst-py/.sst/artifacts/c8e724473dea4ba7e3c24ed8758fa55c990c9fe7a6
    at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
    at new SystemError (node:internal/errors:238:5)
    at new NodeError (node:internal/errors:349:7)
    at checkPaths (node:internal/fs/cp/cp:109:11)
    at async cpFn (node:internal/fs/cp/cp:65:17)
    at async Object.build (file:///Users/mitch/<dir>/sst-py/node_modules/sst/runtime/handlers/python.js:79:13)
    at async task (file:///Users/mitch/<dir>/sst-py/node_modules/sst/runtime/handlers.js:34:31)
    at async Object.build (file:///Users/mitch/<dir>/sst-py/node_modules/sst/runtime/handlers.js:78:23)
    at async file:///Users/mitch/<dir>/sst-py/node_modules/sst/constructs/Function.js:188:32
    at process.<anonymous> (file:///Users/mitch/<dir>/sst-py/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

### Reproduction steps

1. Have any function with a `python3.*` rutime configured
2. Run `sst build` or `sst deploy`
3. Get this error

**Comment by ecumene** [comment]
I think the issue is here:

https://github.com/serverless-stack/sst/blob/2e897bc8beb343a70b9e3911e83e67d758e93fbd/packages/sst/src/runtime/handlers/python.ts#L88

**Comment by ecumene** [comment]
This seems to fix it (?)

```py
      await fs.cp(input.out, src + "/", {
        recursive: true,
        filter: (src) => {
          if (src.includes(".sst")) return false;
          return true;
        },
      });
```
