### ISSUE TITLE
sst diff fails with error for new stacks

### ISSUE THREAD

**Issue by teyckmans** [serverless-stack/sst#2789]
Running sst diff fails with a validation error when adding a new stack that doesn't exist in a target environment.

This is problematic when running sst diff as part of CI pipelines as jobs can't depend on the diff job running successfully when you add new stacks.

Example error:
`
Error: Stack with id SomeNewStack does not exist
Trace: ValidationError: Stack with id SomeNewStack does not exist
    at throwDefaultError (/builds/runner/13/my-service/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_queryGetTemplateCommandError (/builds/runner/13/my-service/node_modules/@aws-sdk/client-cloudformation/dist-cjs/protocols/Aws_query.js:2101:51)
...
`

**Comment by jayair** [comment]
Can we post this on #help on Discord? It'll help us track it and fix it.

**Comment by fwang** [comment]
Fixed in v2.7.2
