### ISSUE TITLE
quickstart-astro example is broken for npm run preview

### ISSUE THREAD

**Issue by JPVan** [serverless-stack/sst#3060]
I get the following error when trying `npm run preview` in the quickstart-astro example. Is this supposed to work? If not, I'm happy to make a pull request to take this out of package.json and readme.md. 

sst/examples/quickstart-astro$ npm run preview

> quickstart-astro@0.0.0 preview
> astro preview

 error   [preview] The astro-sst/lambda adapter does not support the preview command.
  File:
    /home/jp/dev/sst/examples/quickstart-astro/node_modules/astro/dist/core/preview/index.js:39:11
  Code:
    38 |   if (!settings.adapter.previewEntrypoint) {
    > 39 |     throw new Error(
         |           ^
      40 |       `[preview] The ${settings.adapter.name} adapter does not support the preview command.`
      41 |     );
      42 |   }
  Stacktrace:
Error: [preview] The astro-sst/lambda adapter does not support the preview command.
    at preview (file:///home/jp/dev/sst/examples/quickstart-astro/node_modules/astro/dist/core/preview/index.js:39:11)
    at async runCommand (file:///home/jp/dev/sst/examples/quickstart-astro/node_modules/astro/dist/cli/index.js:200:22)
    at async cli (file:///home/jp/dev/sst/examples/quickstart-astro/node_modules/astro/dist/cli/index.js:213:5)

**Comment by jayair** [comment]
Do you mind posting this on #help on Discord? I'll get the team to take a look.

**Comment by JPVan** [comment]
Sure thing.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
