### ISSUE TITLE
Type error: Property 'public' does not exist on type 'BucketResources'.

### ISSUE THREAD

**Issue by zhifez** [serverless-stack/sst#3065]
Was following through the [Next.JS tutorial](https://docs.sst.dev/start/nextjs), up until the deploy to prod section using the following command:
`yarn sst deploy --stage prod`

I received the following errors in the log:
```
Type error: Property 'public' does not exist on type 'BucketResources'.

  11 |   const list = await client.send(
  12 |     new ListObjectsCommand({
> 13 |       Bucket: Bucket.public.bucketName,
     |                      ^
  14 |     })
  15 |   );
  16 | 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:internal/errors:856
  const err = new Error(message);
              ^

Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:841:11)
    at Object.execSync (node:child_process:912:15)
    at buildNextjsApp (file:///Users/user-name/.npm/_npx/061b510618b8a5c9/node_modules/open-next/dist/build.js:90:8)
    at build (file:///Users/user-name/.npm/_npx/061b510618b8a5c9/node_modules/open-next/dist/build.js:22:11)
    at file:///Users/user-name/.npm/_npx/061b510618b8a5c9/node_modules/open-next/dist/index.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5414,
  stdout: null,
  stderr: null
}
Error: There was a problem building the "site" site.

Trace: Error: There was a problem building the "site" site.
    at NextjsSite.runBuild (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/constructs/SsrSite.js:293:19)
    at NextjsSite.buildApp (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/constructs/SsrSite.js:255:18)
    at file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/constructs/SsrSite.js:115:18
    at runTask (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/constructs/deferred_task.js:29:21)
    at file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/constructs/deferred_task.js:40:21
    at new Promise (<anonymous>)
    at Object.run (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/constructs/deferred_task.js:17:20)
    at App.finish (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/constructs/App.js:191:34)
    at Module.synth (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/stacks/synth.js:56:19)
    at async file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/cli/commands/deploy.js:74:24
    at async Object.handler (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/cli/commands/deploy.js:65:22)
    at process.<anonymous> (file:///Users/user-name/git/aws/video-stream-system/video-stream-next/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:167:25)
    at processPromiseRejections (node:internal/process/promises:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

P.S. It's not a duplicate of [2790](https://github.com/serverless-stack/sst/issues/2790) issue as my issue happens during deployment to prod.

**Comment by zhifez** [comment]
Found a temporary fix, probably not the most elegant one:
```
import { Bucket as S3Bucket } from 'aws-cdk-lib/aws-s3';
import { Bucket } from 'sst/node/bucket';

export async function handler() {
  if (!('public' in Bucket)) {
    return;
  }

  const bucket = Bucket.public as S3Bucket;

  const client = new S3Client({});

  const list = await client.send(
    new ListObjectsCommand({
      Bucket: bucket.bucketName,
    })
  );
  ...
}
```

**Comment by jayair** [comment]
I think we rolled out a fix for this.
